using System;
using Confluent.Kafka;

namespace Kafka.Streams.Errors
{
    /**
     * {@link StreamsException} is the top-level exception type generated by Kafka Streams.
     */
    public class StreamsException : KafkaException
    {
        public StreamsException(Error error)
            : base(error)
    {
    }

    public StreamsException(ErrorCode code)
        : base(code)
    {
    }

    public StreamsException(Error error, Exception innerException)
        : base(error, innerException)
    {
    }
}