using System;
using Confluent.Kafka;

namespace Kafka.Streams.Errors
{
    /**
     * {@link StreamsException} is the top-level exception type generated by Kafka Streams.
     */
    public class StreamsException : Exception
    {
        private readonly string message = "";
        private readonly Exception exception;

        public StreamsException(Exception exception)
        {
            this.exception = exception;
        }

        public StreamsException(string message)
        {
            this.message = message;
        }

        public StreamsException(string message, Exception exception)
        {
            this.message = message;
        }
    }
}
